FROM ontotext/graphdb:10.7.4

LABEL org.opencontainers.image.source="https://github.com/MaastrichtU-CDS/Flyover"
LABEL org.opencontainers.image.description="Reference to GraphDB for Flyover project"
LABEL org.opencontainers.image.licenses="https://graphdb.ontotext.com/documentation/10.7/licensing.html"